name: Build

on:
  push:
    branches: [ master ]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build-test-release:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: 'This should fail.'
        run: asd 123;

      - uses: doitadrian/action-post@master
        with:
          command: echo "this thing works!"

      - uses: doitadrian/action-post@master
        with:
          command: echo "this thing works again!"
