on: issue_comment
name: Issue Comments

jobs:
  check_comments:
    name: Check comments for /test
    runs-on: ubuntu-latest
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: test
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: admin
      - name: Act on the command
        run: echo "The command was '${{ steps.command.outputs.command-name }}' with arguments '${{ steps.command.outputs.command-arguments }}'"


      - name: wtf
        run: echo "The operating system on the runner is not Windows, it's $GITHUB_SERVER_URL."

      - name: wtf2
        run: echo "The operating system on the runner is not Windows, it's $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID."

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Cypress E2E tests have been initiated (for more information, click [here](${{ GITHUB_SERVER_URL }})). :sparkles:"

