name: Pull Requests

on:
  pull_request:
    branches: [master]

jobs:
  # This first step ensures we don't run the workflow if the repository is empty.
  # Feel free to remove this step once your project is pushed to the repository.
  repository-check:
    name: Check if repository is empty
    runs-on: ubuntu-latest
    outputs:
      ready: ${{ steps.webiny-project-js.outputs.ready }}
    steps:
      - uses: actions/checkout@v2

      - name: Check if "webiny.project.js" exists
        id: webiny-project-js
        run: echo "::set-output name=ready::${{ hashFiles('webiny.project.ts') != '' }}"

  build-test-static-unit:
    name: Build and run static and unit tests
    needs: repository-check
    runs-on: ubuntu-latest
    if: needs.repository-check.outputs.ready == 'true'
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - uses: actions/checkout@v2
