name: Pull Requests

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check if "webiny.project.js" exists
        id: webiny-project-js
        run: echo "YES"

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Check if "webiny.project.js" exists
        id: webiny-project-js
        run: echo "NO"
