on:
  workflow_dispatch:
  repository_dispatch:
    types: [prepare-release-notes]

jobs:
  aws-nuke:
    runs-on: ubuntu-latest
    steps:
      with:
        ref: webiny-${{ github.event.client_payload.toVersion }}

      - name: Install dependencies
        run: yarn --immutable

      - name: run
        run: node create-file.js

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Webiny ${{ github.event.client_payload.toVersion }}
          body: Creates the Webiny ${{ github.event.client_payload.toVersion }} release notes.

