on:
  workflow_dispatch:
  repository_dispatch:
    types: [prepare-release-notes]

jobs:
  create-release-notes:
    needs: create-branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn --immutable

      - name: run
        run: node create-file.js

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Webiny ${{ github.event.client_payload.toVersion }}
          body: Creates the Webiny ${{ github.event.client_payload.toVersion }} release notes.
          branch: webiny-${{ github.event.client_payload.toVersion }}
