on:
  push:
    branches:
      - "webiny-*"

jobs:
  aws-nuke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: sad
          body: sad
